// All user-facing Sinhala text strings
export const SI = {
  // App
  appName: 'වටහපත්',
  appTagline: 'ශ්‍රී ලාංකික නිෂ්පාදන වෙළඳපොළ',

  // Nav
  home: 'මුල් පිටුව',
  products: 'නිෂ්පාදන',
  categories: 'වර්ග',
  cart: 'කූඩය',
  orders: 'ඇණවුම්',
  dashboard: 'පාලක පුවරුව',
  profile: 'පැතිකඩ',
  logout: 'පිටවීම',
  login: 'පිවිසීම',
  register: 'ලියාපදිංචිය',

  // Auth
  email: 'විද්‍යුත් ලිපිනය',
  password: 'මුරපදය',
  confirmPassword: 'මුරපදය තහවුරු කරන්න',
  fullName: 'සම්පූර්ණ නම',
  phone: 'දුරකථන අංකය',
  address: 'ලිපිනය',
  loginTitle: 'ගිණුමට පිවිසෙන්න',
  loginSubtitle: 'ඔබේ ගිණුමට ස්වාගතයි',
  registerTitle: 'නව ගිණුමක් සාදන්න',
  registerSubtitle: 'වටහපත් ප්‍රජාවට සම්බන්ධ වන්න',
  noAccount: 'ගිණුමක් නැද්ද?',
  haveAccount: 'ගිණුමක් තිබේද?',
  registerHere: 'ලියාපදිංචි වන්න',
  loginHere: 'පිවිසෙන්න',
  selectRole: 'ගිණුම් වර්ගය තෝරන්න',
  roleCustomer: 'ගනුදෙනුකරු',
  roleProducer: 'නිෂ්පාදකයා',
  forgotPassword: 'මුරපදය අමතකද?',

  // Roles
  admin: 'පරිපාලක',
  producer: 'නිෂ්පාදකයා',
  customer: 'ගනුදෙනුකරු',

  // Products
  addProduct: 'නිෂ්පාදනයක් එකතු කරන්න',
  editProduct: 'නිෂ්පාදනය සංස්කරණය කරන්න',
  deleteProduct: 'නිෂ්පාදනය ඉවත් කරන්න',
  productName: 'නිෂ්පාදනයේ නම',
  productDesc: 'විස්තරය',
  productPrice: 'මිල (රු.)',
  productCategory: 'වර්ගය',
  productStock: 'ප්‍රමාණය',
  productImage: 'රූපය',
  inStock: 'තොගයේ ඇත',
  outOfStock: 'තොගයේ නැත',
  addToCart: 'කූඩයට එකතු කරන්න',
  buyNow: 'දැන්ම මිලදී ගන්න',
  viewDetails: 'විස්තර බලන්න',
  price: 'මිල',
  stock: 'තොගය',
  category: 'වර්ගය',
  manageProducts: 'නිෂ්පාදන කළමනාකරණය',
  allProducts: 'සියලු නිෂ්පාදන',
  myProducts: 'මගේ නිෂ්පාදන',
  productSearch: 'නිෂ්පාදන සොයන්න...',
  noProducts: 'නිෂ්පාදන හමු නොවීය',

  // Categories — Athu (Arecanut/Betelnut) varieties
  exprayAthu: 'එක්ස්ප්‍රේ අත්ත',
  normalAthu: 'සාමාන්‍ය අත්ත',
  rendaAthu: 'රේන්ද අත්ත',
  thalakolaAthu: 'තළකොළ අත්ත',
  ribbonAthu: 'රිබන් අත්ත',
  allCategories: 'සියලු වර්ග',

  // Legacy labels kept for other pages
  vegetables: 'එළවළු',

  // Orders
  myOrders: 'මගේ ඇණවුම්',
  orderHistory: 'ඇණවුම් ඉතිහාසය',
  orderDetails: 'ඇණවුමේ විස්තර',
  orderStatus: 'ඇණවුම් තත්ත්වය',
  orderDate: 'ඇණවුම් දිනය',
  orderTotal: 'මුළු මිල',
  orderItems: 'ඇණවුම් අයිතම',
  placeOrder: 'ඇණවුම ලබා දෙන්න',
  cancelOrder: 'ඇණවුම අවලංගු කරන්න',
  updateStatus: 'තත්ත්වය යාවත්කාලීන කරන්න',
  pending: 'අපේක්ෂිතයි',
  confirmed: 'තහවුරු කළා',
  processing: 'සකසමින්',
  shipped: 'යවා ඇත',
  delivered: 'ලබා දෙන ලදී',
  cancelled: 'අවලංගු කළා',
  manageOrders: 'ඇණවුම් කළමනාකරණය',
  allOrders: 'සියලු ඇණවුම්',
  receivedOrders: 'ලැබුණු ඇණවුම්',
  expectedDate: "අවශ්‍ය දිනය​",

  // Cart
  cartTitle: 'සාප්පු කූඩය',
  cartEmpty: 'කූඩය හිස්ය',
  cartEmptyDesc: 'ඔබේ කූඩයේ නිෂ්පාදන නොමැත',
  removeFromCart: 'කූඩයෙන් ඉවත් කරන්න',
  quantity: 'ප්‍රමාණය',
  subtotal: 'උප එකතුව',
  total: 'මුළු එකතුව',
  checkout: 'ගෙවීමට යන්න',
  continueShopping: 'සාප්පු යාම දිගටම කරන්න',

  // Admin
  userManagement: 'පරිශීලක කළමනාකරණය',
  productManagement: 'නිෂ්පාදන කළමනාකරණය',
  orderManagement: 'ඇණවුම් කළමනාකරණය',
  totalUsers: 'සම්පූර්ණ පරිශීලකයන්',
  totalProducts: 'සම්පූර්ණ නිෂ්පාදන',
  totalOrders: 'සම්පූර්ණ ඇණවුම්',
  totalRevenue: 'සම්පූර්ණ ආදායම',
  approveProducer: 'නිෂ්පාදකයා අනුමත කරන්න',
  rejectProducer: 'ප්‍රතික්ෂේප කරන්න',
  approved: 'අනුමත කළා',
  rejected: 'ප්‍රතික්ෂේප කළා',
  pending_approval: 'අනුමත කිරීම් බලාපොරොත්තු',
  allUsers: 'සියලු පරිශීලකයන්',
  customers: 'ගනුදෙනුකරුවන්',
  producers: 'නිෂ්පාදකයන්',
  deactivate: 'අක්‍රිය කරන්න',
  activate: 'සක්‍රිය කරන්න',
  active: 'සක්‍රිය',
  inactive: 'අක්‍රිය',

  // Common
  save: 'සුරකින්න',
  cancel: 'අවලංගු කරන්න',
  delete: 'මකන්න',
  edit: 'සංස්කරණය',
  view: 'බලන්න',
  search: 'සොයන්න',
  filter: 'පෙරහන',
  sort: 'වර්ග කරන්න',
  actions: 'ක්‍රියාකාරකම්',
  status: 'තත්ත්වය',
  name: 'නම',
  description: 'විස්තරය',
  createdAt: 'සාදන ලද දිනය',
  updatedAt: 'යාවත්කාලීන කළ දිනය',
  loading: 'පූරණය වෙමින්...',
  error: 'දෝෂය',
  success: 'සාර්ථකයි',
  confirm: 'තහවුරු කරන්න',
  close: 'වසන්න',
  back: 'ආපසු',
  next: 'ඊළඟ',
  previous: 'පෙර',
  noData: 'දත්ත නොමැත',
  required: 'අවශ්‍ය',
  optional: 'අත්‍යාවශ්‍ය නොවේ',
  rs: 'රු.',
  unit: 'ඒකක',
  kg: 'කිලෝ',
  gram: 'ග්‍රෑම්',
  liter: 'ලීටර',
  piece: 'කෑලි',
  welcome: 'ආයුබෝවන්',
  welcomeBack: 'නැවත ස්වාගතයි',
  shopNow: 'දැන්ම සාප්පු යන්න',
  featuredProducts: 'විශේෂ නිෂ්පාදන',
  newArrivals: 'නව ලැබීම්',
  popularProducts: 'ජනප්‍රිය නිෂ්පාදන',
  viewAll: 'සියල්ල බලන්න',
  producerDashboard: 'නිෂ්පාදක පාලක පුවරුව',
  adminDashboard: 'පරිපාලක පාලක පුවරුව',
  customerDashboard: 'ගනුදෙනුකරු පාලක පුවරුව',
  recentOrders: 'මෑත ඇණවුම්',
  recentProducts: 'මෑත නිෂ්පාදන',
}

export const ROLES = {
  ADMIN: 'admin',
  PRODUCER: 'producer',
  CUSTOMER: 'customer',
}

export const ORDER_STATUS = {
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  PROCESSING: 'processing',
  SHIPPED: 'shipped',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
}

export const ORDER_STATUS_SI = {
  pending: SI.pending,
  confirmed: SI.confirmed,
  processing: SI.processing,
  shipped: SI.shipped,
  delivered: SI.delivered,
  cancelled: SI.cancelled,
}

export const ORDER_STATUS_COLORS = {
  pending: 'badge-yellow',
  confirmed: 'badge-blue',
  processing: 'badge-orange',
  shipped: 'badge-blue',
  delivered: 'badge-green',
  cancelled: 'badge-red',
}

export const CATEGORIES = [
  {
    id: 'exprayAthu',
    label: SI.exprayAthu,
    icon: '🌴',
    image: 'images/categories/Expray_Athu.webp',
  },
  {
    id: 'normalAthu',
    label: SI.normalAthu,
    icon: '🥥',
    image: 'images/categories/normal_Athu.jfif',
  },
  {
    id: 'rendaAthu',
    label: SI.rendaAthu,
    icon: '🌿',
    image: 'images/categories/Renda_Athu.jpeg',
  },
  {
    id: 'thalakolaAthu',
    label: SI.thalakolaAthu,
    icon: '🍃',
    image: 'images/categories/thalakola_Athu.jpeg',
  },
  {
    id: 'ribbonAthu',
    label: SI.ribbonAthu,
    icon: '🎗️',
    image: 'images/categories/Ribbon_Athu.jpg',
  },
]
